name: Front-end CI

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "src/**"
  #     - "**/*.js"
  # pull_request:
  #   types: [opened, synchronize, reopened]
    

jobs:
  Analysis:
    name: SonarQube Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x,  21.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build run
      run: npm run build --if-present
      env:
        CI: ""

    - name: Test run
      run: npm test -- --watchAll=false
      env:
        CI: ""